/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selec;

/**
 *
 * @author PC-12
 */
public class LosaTipo extends javax.swing.JFrame {

    /**
     * Creates new form Losa
     */
    public LosaTipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Losa1 = new javax.swing.JLabel();
        Losa2 = new javax.swing.JLabel();
        Losa3 = new javax.swing.JLabel();
        Losa4 = new javax.swing.JLabel();
        Losa5 = new javax.swing.JLabel();
        Losa6 = new javax.swing.JLabel();
        Losa7 = new javax.swing.JLabel();
        Losa8 = new javax.swing.JLabel();
        Losa9 = new javax.swing.JLabel();
        SeleccionLosa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Losa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa1MouseClicked(evt);
            }
        });
        getContentPane().add(Losa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 130));

        Losa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa2MouseClicked(evt);
            }
        });
        getContentPane().add(Losa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 130));

        Losa3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa3MouseClicked(evt);
            }
        });
        getContentPane().add(Losa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 130, 130));

        Losa4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa4MouseClicked(evt);
            }
        });
        getContentPane().add(Losa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 130));

        Losa5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa5MouseClicked(evt);
            }
        });
        getContentPane().add(Losa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 140, 140));

        Losa6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa6MouseClicked(evt);
            }
        });
        getContentPane().add(Losa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 140));

        Losa7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa7MouseClicked(evt);
            }
        });
        getContentPane().add(Losa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 130, 140));

        Losa8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa8MouseClicked(evt);
            }
        });
        getContentPane().add(Losa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 140, 140));

        Losa9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Losa9MouseClicked(evt);
            }
        });
        getContentPane().add(Losa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 140, 140));

        SeleccionLosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        SeleccionLosa.setText("jLabel3");
        getContentPane().add(SeleccionLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Losa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa1MouseClicked
        CalculoCoeficiente.Buscal1(CalculoCoeficiente.divide, LosaLxLy.pos);
        new Losa1Resultado().setVisible(true);       
    }//GEN-LAST:event_Losa1MouseClicked

    private void Losa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa2MouseClicked

    private void Losa3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa3MouseClicked

    private void Losa4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa4MouseClicked

    private void Losa5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa5MouseClicked

    private void Losa6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa6MouseClicked

    private void Losa7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa7MouseClicked

    private void Losa8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa8MouseClicked

    private void Losa9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Losa9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Losa9MouseClicked

    
 /*   public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Losa1;
    private javax.swing.JLabel Losa2;
    private javax.swing.JLabel Losa3;
    private javax.swing.JLabel Losa4;
    private javax.swing.JLabel Losa5;
    private javax.swing.JLabel Losa6;
    private javax.swing.JLabel Losa7;
    private javax.swing.JLabel Losa8;
    private javax.swing.JLabel Losa9;
    private javax.swing.JLabel SeleccionLosa;
    // End of variables declaration//GEN-END:variables
}
