/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selec;

import java.util.ArrayList;

/**
 *
 * @author PC01
 */
public class LosaLxLy extends javax.swing.JFrame {
    public static boolean pos;
    public static ArrayList <Losa1Coef> Losa1Arr = new ArrayList <Losa1Coef>(); 
    /**
     * Creates new form Losa1LxLy
     */
    public LosaLxLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lx = new javax.swing.JTextField();
        Ly = new javax.swing.JTextField();
        ACEPTAR = new javax.swing.JLabel();
        MenuLxLy = new javax.swing.JLabel();
        INGRESETC = new javax.swing.JLabel();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(320, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LxActionPerformed(evt);
            }
        });
        getContentPane().add(Lx, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 160, 20));
        getContentPane().add(Ly, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 160, -1));

        ACEPTAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACEPTARMouseClicked(evt);
            }
        });
        getContentPane().add(ACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 160, 60));

        MenuLxLy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BOTONLXLY.jpg"))); // NOI18N
        getContentPane().add(MenuLxLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 240, 240));

        INGRESETC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        INGRESETC.setForeground(new java.awt.Color(255, 255, 255));
        INGRESETC.setText("Ingrese los valores de Lx y Ly:");
        getContentPane().add(INGRESETC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 270, 70));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/xd2.jpg"))); // NOI18N
        getContentPane().add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 340, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LxActionPerformed
       
    }//GEN-LAST:event_LxActionPerformed

    private void ACEPTARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACEPTARMouseClicked
        double numLx=Double.parseDouble(Lx.getText());
        double numLy=Double.parseDouble(Ly.getText());
        pos = CalculoCoeficiente.dividir(numLx, numLy); 
        new LosaTipo().setVisible(true);
    }//GEN-LAST:event_ACEPTARMouseClicked

   
    public static void main(String args[]) {
         
        Losa1Arr.add(new Losa1Coef(0.50,0.0965,0.0174,0.269,0.731,true));
        Losa1Arr.add(new Losa1Coef(0.55,0.0892,0.0210,0.268,0.641,true));
        Losa1Arr.add(new Losa1Coef(0.60,0.0820,0.0243,0.267,0.566,true));
        Losa1Arr.add(new Losa1Coef(0.65,0.0750,0.0273,0.266,0.502,true));
        Losa1Arr.add(new Losa1Coef(0.70,0.0683,0.0298,0.265,0.450,true));
        Losa1Arr.add(new Losa1Coef(0.75,0.0619,0.0318,0.263,0.404,true));
        Losa1Arr.add(new Losa1Coef(0.80,0.0560,0.0334,0.261,0.364,true));
        Losa1Arr.add(new Losa1Coef(0.85,0.0506,0.0348,0.259,0.330,true));
        Losa1Arr.add(new Losa1Coef(0.90,0.0456,0.0359,0.256,0.300,true));
        Losa1Arr.add(new Losa1Coef(0.95,0.0410,0.0365,0.253,0.274,true));
        Losa1Arr.add(new Losa1Coef(1,0.0368,0.0368,0.250,0.250,true));
        
        Losa1Arr.add(new Losa1Coef(0.50,0.0965,0.0174,0.269,0.731,false));
        Losa1Arr.add(new Losa1Coef(0.55,0.0892,0.0210,0.268,0.641,false));
        Losa1Arr.add(new Losa1Coef(0.60,0.0820,0.0243,0.267,0.566,false));
        Losa1Arr.add(new Losa1Coef(0.65,0.0750,0.0273,0.266,0.502,false));
        Losa1Arr.add(new Losa1Coef(0.70,0.0683,0.0298,0.265,0.450,false));
        Losa1Arr.add(new Losa1Coef(0.75,0.0619,0.0318,0.263,0.404,false));
        Losa1Arr.add(new Losa1Coef(0.80,0.0560,0.0334,0.261,0.364,false));
        Losa1Arr.add(new Losa1Coef(0.85,0.0506,0.0348,0.259,0.330,false));
        Losa1Arr.add(new Losa1Coef(0.90,0.0456,0.0359,0.256,0.300,false));
        Losa1Arr.add(new Losa1Coef(0.95,0.0410,0.0365,0.253,0.274,false));
        Losa1Arr.add(new Losa1Coef(1,0.0368,0.0368,0.250,0.250,false));
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LosaLxLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACEPTAR;
    private javax.swing.JLabel FONDO;
    private javax.swing.JLabel INGRESETC;
    private javax.swing.JTextField Lx;
    private javax.swing.JTextField Ly;
    private javax.swing.JLabel MenuLxLy;
    // End of variables declaration//GEN-END:variables
}
